# Generated by Django 5.2.14 on 2026-05-27 11:32

import linkedin.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_deal_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('Qualified', 'Qualified'), ('Ready to Connect', 'Ready to Connect'), ('Pending', 'Pending'), ('Connected', 'Connected'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Escalated', 'Escalated'), ('Waiting Approval', 'Waiting Approval')], default=linkedin.enums.ProfileState['QUALIFIED'], max_length=20),
        ),
    ]
