# Generated by Django 5.2.14 on 2026-05-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_deal_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
