# Generated by Django 5.2.14 on 2026-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_deal_connected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='connect_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
