# Generated by Django 5.2.14 on 2026-05-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_deal_connect_sent_at'),
        ('linkedin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='linkedin_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='linkedin.linkedinprofile'),
        ),
    ]
