# Generated by Django 5.2.14 on 2026-05-28 17:33
import logging
from django.db import migrations

logger = logging.getLogger(__name__)


def backfill_deal_timestamps(apps, schema_editor):
    Deal = apps.get_model('crm', 'Deal')
    LinkedInProfile = apps.get_model('linkedin', 'LinkedInProfile')
    db_alias = schema_editor.connection.alias

    count = 0
    for deal in Deal.objects.using(db_alias).all():
        changed = False

        # 1. Backfill linkedin_profile if missing
        if not deal.linkedin_profile_id:
            # Look up a profile whose user is associated with the deal's campaign
            profile = LinkedInProfile.objects.using(db_alias).filter(user__campaigns=deal.campaign).first()
            if profile:
                deal.linkedin_profile = profile
                changed = True

        # 2. Backfill connected_at and connect_sent_at
        state_str = str(deal.state).lower()
        if state_str in ['connected', 'completed', 'escalated', 'waiting_approval']:
            if not deal.connected_at:
                deal.connected_at = deal.update_date or deal.creation_date
                changed = True
            if not deal.connect_sent_at:
                deal.connect_sent_at = deal.creation_date
                changed = True
        elif state_str == 'pending':
            if not deal.connect_sent_at:
                deal.connect_sent_at = deal.creation_date or deal.update_date
                changed = True

        if changed:
            deal.save()
            count += 1

    if count > 0:
        print(f"\nBackfilled {count} existing Deal timestamp and profile association records successfully.")


def rollback_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_deal_linkedin_profile'),
        ('linkedin', '0014_encrypt_existing_cookies'),
    ]

    operations = [
        migrations.RunPython(backfill_deal_timestamps, rollback_backfill),
    ]
