# Generated by Django 5.2.14 on 2026-05-23 12:06

import linkedin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0008_delete_freemium_campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinprofile',
            name='linkedin_password',
            field=linkedin.models.EncryptedCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='linkedinprofile',
            name='subscribe_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='llm_api_key',
            field=linkedin.models.EncryptedCharField(blank=True, default='', max_length=500),
        ),
    ]
