# Generated by Django 5.2.14 on 2026-05-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_deal_state'),
        ('linkedin', '0010_encrypt_existing_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approval_mode',
            field=models.CharField(choices=[('auto', 'Auto — AI gửi tự do'), ('first_touch', 'First Touch — Approve tin đầu tiên'), ('high_intent', 'High Intent — Approve khi intent ≥ medium hoặc needs_human'), ('all', 'All — Approve mọi tin nhắn')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('send_approved_message', 'Send Approved Message')], max_length=30),
        ),
        migrations.CreateModel(
            name='AgentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_message', models.TextField()),
                ('corrected_message', models.TextField(blank=True, default='')),
                ('feedback_type', models.CharField(choices=[('approved', 'Approved'), ('edited', 'Edited'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='linkedin.campaign')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.deal')),
            ],
        ),
        migrations.CreateModel(
            name='PendingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('decision_json', models.JSONField()),
                ('telegram_message_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_message', to='crm.deal')),
            ],
        ),
    ]
