# Generated by Django 5.2.14 on 2026-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0011_campaign_approval_mode_alter_task_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='original_connect_daily_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('send_approved_message', 'Send Approved Message'), ('withdraw_old_invites', 'Withdraw Old Invites')], max_length=30),
        ),
    ]
