# Generated by Django 5.2.14 on 2026-05-28 09:43

import linkedin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0012_linkedinprofile_original_connect_daily_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinprofile',
            name='cookie_data',
            field=linkedin.models.EncryptedJSONField(blank=True, null=True),
        ),
    ]
