# Generated by Django 5.2.14 on 2026-05-28 10:11
import logging
from django.db import migrations

logger = logging.getLogger(__name__)


def encrypt_existing_cookies(apps, schema_editor):
    LinkedInProfile = apps.get_model('linkedin', 'LinkedInProfile')
    db_alias = schema_editor.connection.alias

    count = 0
    for profile in LinkedInProfile.objects.using(db_alias).all():
        if profile.cookie_data:
            # Accessing profile.cookie_data triggers the ORM to load and decrypt (or keep as-is if plaintext).
            # Then calling save(update_fields=['cookie_data']) triggers get_prep_value() of EncryptedJSONField,
            # which serializes to JSON and encrypts via Fernet, saving the secure ciphertext to the DB.
            profile.save(update_fields=['cookie_data'])
            count += 1
            
    if count > 0:
        print(f"\nEncrypted {count} existing LinkedInProfile cookie records successfully.")


def decrypt_existing_cookies(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0013_alter_linkedinprofile_cookie_data'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_cookies, decrypt_existing_cookies),
    ]
